version: '2'
networks:
  dev_network:
    driver: bridge

volumes:
  mongodb_data:

services:
  mongo-db:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: projectX9
    ports:
      - 27017:27017
    volumes:
        - mongodb_data:/data/db
        -

  mongo-express:
    image: mongo-express
    restart: always
    depends_on:
      - mongo-db
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://root:password@mongo-db:27017/
